import { StyleSheet, Dimensions, Platform } from "react-native";

import { StatusBar } from "expo-status-bar";

// Custom style constants
import Colors from "@/constants/Colors";
import Sizes from "@/constants/Sizes";

// Styles for the app
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
    // Ensure content is not getting cut off due to status bar
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
  italic: {
    fontStyle: "italic",
  },
  imageContainer: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: Colors.background,
  },
  portraitImage: {
    height: "100%",
    width: "100%",
    resizeMode: "cover",
  },
  landscapeImage: {
    height: "100%",
    width: "100%",
  },
  safeAreaContainer: {
    flex: 1,
    paddingHorizontal: Sizes.paddingHorizontal,
    justifyContent: "space-between",
    backgroundColor: "transparent",
  },
  safeAreaContainerAuth: {
    zIndex: 1,
  },
  textContainer: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.shadowBg,
    padding: 10,
    paddingTop: 40,
    marginTop: Sizes.topSpace,
  },
  textContainerAuth: {
    backgroundColor: Colors.shadowBg,
    marginTop: Sizes.topSpace,
    marginBottom: 20,
    padding: 30,
  },
  textContainerAuthLandscape: {
    backgroundColor: Colors.shadowBg,
    padding: 5,
    marginTop: 2,
    marginBottom: 5,
  },
  landscapeTextContainer: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.shadowBg,
    padding: 20,
    marginTop: 40,
    marginBottom: 20,
  },
  appName: {
    fontSize: Sizes.fontSizeTitle,
    color: Colors.indexPrimary,
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
    marginBottom: 20,
  },
  pixelPanel: {
    backgroundColor: "rgba(0,0,0,0.55)",
    borderWidth: 4,
    borderColor: Colors.mainBorder,
    padding: 12,
    borderRadius: 4,
    // “pixel shadow” effect
    shadowColor: "#000",
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  pixelTitle: {
    color: Colors.indexPrimary,
    fontWeight: "bold",
  },
  pixelSubtleText: {
    marginTop: 10,
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
  },
  pixelInfoText: {
    marginTop: 10,
    textAlign: "center",
    color: Colors.mainBorder,
  },
  formPanel: {
    marginTop: 12,
    padding: 12,
  },
  mainTitle: {
    fontSize: Sizes.fontSizeTitleSubPages,
    color: Colors.indexPrimary,
    textAlign: "center",
  },
  subTitleText: {
    fontSize: 18,
    letterSpacing: 1,
    color: Colors.subtitlePrimary,
    marginTop: 10,
    textAlign: "center",
    textShadowColor: "#000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
  },
  buttonContainer: {
    marginBottom: 20,
  },
  textCenter: {
    textAlign: "center",
  },
  formScroll: {
    flexGrow: 1,
    justifyContent: "center",
  },
  input: {
    borderWidth: 4,
    borderColor: Colors.buttonBorderColor,
    padding: 8,
    borderRadius: 4,
    marginBottom: 16,
    backgroundColor: Colors.buttonFormBC,
    color: Colors.buttonFormFont,
    fontSize: Sizes.fontSmall,
  },
  inputLandscape: {
    borderWidth: 3,
    borderColor: Colors.buttonBorderColor,
    padding: 5,
    borderRadius: 4,
    marginBottom: Sizes.bottomSpace,
    backgroundColor: Colors.buttonFormBC,
    color: Colors.buttonFormFont,
    fontSize: Sizes.fontSmall,
  },
  errorText: {
    color: Colors.warningColor,
    fontSize: Sizes.fontSmall * 1.1,
    marginBottom: Sizes.bottomSpace,
    textAlign: "center",
    fontWeight: "bold",
    backgroundColor: Colors.shadowBg,
  },
  buttonText: {
    fontWeight: "bold",
    fontSize: Sizes.fontSmall * 1.3,
  },
  pressableContainer: {
    position: "absolute",
    top: 10,
    left: 8,
    zIndex: 10,
  },
  pressableContainerLandscape: {
    position: "absolute",
    left: 8,
    zIndex: 10,
  },
  activityIndicator: {
    color: Colors.activityColor,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.shadowBg,
  },
  modalContainer: {
    width: "80%",
    padding: 20,
    backgroundColor: Colors.sutleWhite,
    borderRadius: 10,
    alignItems: "center",
  },
  modalText: {
    textAlign: "center",
    fontSize: Sizes.fontSmall,
    fontWeight: "bold",
    color: Colors.blackDepp,
  },
  // Main app
  homeHeaderPanel: {
    borderWidth: 4,
    borderColor: Colors.mainBorder,
    padding: 12,
    borderRadius: 4,
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    marginBottom: 4,
  },
  settingsButton: {
    left: 300,
  },
  header: {
    flexDirection: "row-reverse",
    marginTop: 20,
    marginBottom: Sizes.bottomSpace,
  },
  backgroundImage: {
    flex: 1,
    borderRadius: 10,
    justifyContent: "center", // Centers the children vertically
    alignItems: "center", // Centers the children horizontally
    borderWidth: 5,
    borderColor: Colors.blackDepp,
  },
  gradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  pressableAboutContainer: {
    position: "absolute",
    top: 10,
    right: 12,
    zIndex: 10,
  },
  pressableAboutContainerLandscape: {
    position: "absolute",
    top: 5,
    right: 10,
    zIndex: 10,
  },
  aboutText: {
    marginTop: 20,
    color: Colors.mainTitle,
    fontSize: 18,
    textAlignVertical: "left",
    flexShrink: 1,
  },
  smallText: {
    color: Colors.mainTitle,
    marginTop: 20,
    fontSize: 15,
    textAlignVertical: "center",
    flexShrink: 1,
  },
  linkText: {
    color: Colors.indexPrimary,
  },
  list: {
    paddingBottom: Sizes.bottomSpace,
  },
  textStyle: {
    color: Colors.secondary,
    position: "relative",
    textAlign: "center" as const,
    fontSize: Sizes.fontSizeSubtitle,
  },
  textListStyle: {
    color: Colors.indexPrimary, // burnt orange title
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center" as const,
    textShadowColor: "rgba(0, 0, 0, 0.85)",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,

    backgroundColor: "rgba(0, 0, 0, 0.55)",
    padding: 5,
  },
  textSmallStyle: {
    color: Colors.mainSubTitle,
    marginLeft: 2,
    marginTop: 4,
    fontSize: Sizes.fontSmall,
    fontWeight: "500" as const,
    textAlign: "left" as const,
  },
  titleStyle: {
    color: Colors.mainTitle,
    flex: 1,
    textAlign: "left",
    paddingRight: 60,
    fontWeight: "bold",
    fontSize: Sizes.fontBig,
  },
  titleStyleAlt: {
    color: Colors.blackDeep,
    flex: 1,
    textAlign: "left",
    paddingRight: 60,
    fontWeight: "bold",
    fontSize: Sizes.fontBig,
  },
  lottiePress: {
    position: "absolute",
    flex: 1,
  },
  lottieAni: {
    width: "100",
    height: "100",
    marginLeft: 5,
    marginRight: 0,
    marginBotton: 20,
  },
  logoutIcon: {
    marginTop: -10,
    alignSelf: "center",
  },
  pressableMain: {
    height: 192,
    marginVertical: 12,
    borderRadius: 4,
    overflow: "hidden",
  },
  flatContainer: {
    flex: 1,
  },
  // Prepare Tasks
  prepareBackground: {
    flex: 1,
  },
  preparePressableBack: {
    position: "absolute",
    top: 30,
    left: 30,
    zIndex: 10,
  },
  prepareContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  prepareContainerLandscape: {
    flex: 1,
    marginTop: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  pixelPreparePanel: {
    backgroundColor: Colors.orangeTitle,
    borderWidth: 4,
    borderColor: Colors.mainBorder,
    padding: 12,
    marginTop: 80,
    marginBottom: 20,
    borderRadius: 4,
    shadowColor: "#000",
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  pixelPrepareTitle: {
    color: Colors.blackDeep,
    fontWeight: "bold",
    fontSize: 26,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  pixelPrepareSubtleText: {
    color: Colors.subtitlePrimary,
    marginTop: 5,
    textAlign: "center",
  },
  preparePage: {
    paddingLeft: 12,
    paddingRight: 12, // keep symmetric
    paddingTop: 0,
  },
  pixelPrepareTaskPanel: {
    backgroundColor: "rgba(0,0,0,0.55)",
    borderWidth: 2,
    borderColor: Colors.mainBorder,
    padding: 8,
    borderRadius: 4,
    // “pixel shadow” effect
    shadowColor: "#000",
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    minHeight: 380,
  },
  pixelPrepareTaskTitle: {
    color: Colors.indexPrimary,
    fontWeight: "bold",
    fontSize: 24,
    marginBottom: 20,
    marginTop: 20,
  },
  swipeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.swipe,
    marginTop: 24,
    padding: 5,
  },
  swipeRowEnd: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 8,
  },
  homeIconSwipe: {
    marginLeft: 10,
  },
  prepareTaskSwipeText: {
    textAlign: "center",
    color: Colors.subtitlePrimary,
  },
  pixelPrepareTaskSubtleText: {
    color: Colors.subtitlePrimary,
    marginTop: 5,
    paddingLeft: 5,
    fontSize: 17,
    textAlign: "left",
    lineHeight: 22,
  },
  progressBarOuter: {
    marginTop: 10,
    height: 14,
    borderRadius: 4,
    overflow: "hidden",
    backgroundColor: "rgba(90, 90, 95, 0.60)",
    borderWidth: 3,
    borderColor: Colors.mainBorder,
    position: "relative",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: Colors.highlightYellow,
  },
  progressLottieWrap: {
    position: "absolute",
    top: -6, // lift slightly so it sits "on" the bar
  },
  timerContainer: {
    backgroundColor: Colors.sutleWhite,
    width: Dimensions.get("window").width * 0.4, // 40% width in portrait
    height: Dimensions.get("window").width * 0.4,
    borderRadius: 1000,
    justifyContent: "center",
    alignItems: "center",
  },
  timerContainerLandscape: {
    backgroundColor: Colors.sutleWhite,
    width: Dimensions.get("window").height * 0.15, // 15% height in landscape
    height: Dimensions.get("window").height * 0.15,
    borderRadius: 1000,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 5,
  },
  timerText: {
    fontSize: 40,
    color: Colors.greenText,
  },
  timerTextLandscape: {
    fontSize: Sizes.fontBig,
    color: Colors.greenText,
  },
  prepareButtons: {
    marginTop: "auto",
    marginBottom: 4,
  },
  prepareButtonsLandscape: {
    marginTop: 3,
    marginBottom: 1,
  },
  creditContainer: {
    backgroundColor: Colors.mainTitleSh,
    width: "auto",
    height: "5%",
    justifyContent: "center",
    alignItems: "center",
    marginTop: -25,
    marginBottom: 20,
  },
  creditContainerLandscape: {
    backgroundColor: Colors.mainTitleSh,
    width: "auto",
    height: "5%",
    justifyContent: "center",
    alignItems: "center",
    marginTop: -10,
    marginBottom: 5,
  },
  quoteCredit: {
    color: Colors.sutleWhite,
    textShadowColor: Colors.shadowBg,
    textShadowOffset: { width: 6, height: 6 },
    textShadowRadius: 14,
  },
  // Change duration
  changeDurContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: Sizes.bottomSpace,
    paddingHorizontal: 20,
    borderWidth: 5,
    borderColor: Colors.blackDepp,
    borderRadius: 20,
  },
  headerText: {
    textAlign: "center",
    fontWeight: "bold",
    fontSize: Sizes.fontSizeTitle,
    letterSpacing: 1,
    color: Colors.mainTitle,

    marginBottom: 50,
    padding: 20,
    borderWidth: 2,
    borderColor: Colors.mainTitle,
    borderStyle: "dashed", // Dashed border style
  },
  headerTextLandscape: {
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 32,
    color: Colors.mainTitle,

    marginBottom: 20,
    letterSpacing: 1.5,

    padding: 5,
    paddingLeft: 100,
    paddingRight: 100,

    borderWidth: 2,
    borderColor: Colors.mainTitle,
    borderStyle: "dashed", // Dashed border style
  },
  buttonGroup: {
    justifyContent: "center",
    width: "100%",
    paddingHorizontal: 10,
  },
  buttonGroupLandscape: {
    justifyContent: "center",
    width: "100%",
    fontSize: 15,
    paddingHorizontal: 20,
  },
  button: {
    backgroundColor: Colors.secondary,
    paddingVertical: 15,
    marginBottom: 15,
    elevation: 5,
  },
  buttonLandscape: {
    backgroundColor: Colors.secondary,
    elevation: 5,
  },
  // Tests
  textTestStyle: {
    color: Colors.blackDeep,
    fontSize: 32,
    fontWeight: "bold",
    marginBottom: 6,
  },
  textTestSmallStyle: {
    color: Colors.mainSubTitle,
    fontSize: 22,
    fontWeight: "bold",
  },
  testsImage: {
    width: Dimensions.get("window").width * 0.4,
    height: Dimensions.get("window").width * 0.3,
    margin: 5,
    borderWidth: 4,
    borderColor: Colors.blackDepp,
    borderRadius: 10,
  },
  testsTitle: {
    borderWidth: 3,
    borderColor: Colors.blackDepp,

    paddingLeft: 15,
    paddingTop: 2,
    paddingBottom: 2,
    fontWeight: "bold",
    fontSize: 20,
  },
  checkList: {
    marginTop: 40,
  },
  feedbackCheckList: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    marginLeft: 35,
  },
  feedbackView: {
    position: "absolute",
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  feedbackItem: {
    marginLeft: 8,
  },
  itemHoverTest: {
    color: Colors.mainBorder,
    fontWeight: "700",
    textAlign: "center",
    padding: 5,

    backgroundColor: "rgba(0, 0, 0, 0.55)",
  },
  pixelTestPanel: {
    backgroundColor: Colors.orangeTitle,
    borderWidth: 4,
    borderColor: Colors.mainBorder,
    padding: 12,
    borderRadius: 4,
    marginTop: 200,
    marginLeft: 10,
    marginRight: 10,
  },
  pixelCheckListPanel: {
    backgroundColor: Colors.gradientQuote,

    borderWidth: 4,
    borderColor: Colors.gradientMainDark,
    borderRadius: 4,

    padding: 10,
    marginTop: 30,
    marginLeft: 10,
    marginRight: 10,
  },
  pixelCheckListTitle: {
    color: Colors.secondary,
    fontWeight: 700,
    fontSize: 18,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "right",
  },
  pixelChecklistRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 10,
    marginBottom: 10,
    backgroundColor: "rgba(0,0,0,0.35)",
    borderWidth: 1,
    borderColor: Colors.mainBorder,
  },
  pixelChecklistRowDone: {
    backgroundColor: "rgba(40, 20, 20, 0.6)",
  },
  pixelChecklistBox: {
    fontSize: 20,
    marginRight: 18,
    color: Colors.secondary,
  },
  pixelChecklistLabel: {
    flex: 1,
    color: Colors.subtitlePrimary,
    fontSize: 16,
    letterSpacing: 0.5,
    marginLeft: 10,
  },
  pixelOrderRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: Colors.mainBorder,
    borderRadius: 4,
    backgroundColor: "rgba(90, 90, 95, 0.55)",
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 6,
  },
  pixelOrderHandle: {
    width: 28,
    textAlign: "center",
    fontSize: 18,
    color: Colors.subtitlePrimary,
    marginRight: 10,
  },
  pixelOrderLabel: {
    flex: 1,
    color: Colors.subtitlePrimary,
    fontSize: 16,
    letterSpacing: 0.5,

    textShadowColor: "rgba(0,0,0,0.7)",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
  },
  pixelOrderCheckButton: {
    paddingVertical: 12,
    borderWidth: 3,
    borderColor: Colors.mainBorder,
    borderRadius: 4,
    backgroundColor: Colors.pink,
    marginTop: 20,

    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  pixelOrderCheckText: {
    textAlign: "center",
    fontWeight: "bold",
    letterSpacing: 1,
    fontSize: 16,
  },
  menuHamburger: {
    marginRight: 14,
  },
  // Resources
  textContainerTest: {
    marginTop: 20,
    marginBottom: 0,
  },
  resource: {
    backgroundColor: Colors.darkPink,
    borderWidth: 3,
    borderColor: Colors.dark,
    padding: 14,
    marginTop: 10,
    marginBottom: 10,
  },
  resourceTitle: {
    fontSize: 18,
    backgroundColor: Colors.orangeTitle,
    marginTop: 5,
  },
  resourceBox: {
    flexDirection: "row",
    alignItems: "center",
  },
  resourceImage: {
    width: 74,
    height: 74,
    marginRight: 5,
    borderWidth: 2,
  },
  resourceInBox: {
    flex: 1,
    marginLeft: 15,
  },
  resourceInText: {
    fontSize: 18,
    textAlign: "left",
  },
  // Components
  safeViewContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  buttonCompContainer: {
    backgroundColor: Colors.sutleWhite,
    minHeight: 62,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 5,
    borderColor: Colors.blackDepp,
    elevation: 5,
  },
  textButtonComp: {
    color: Colors.primary,
    fontWeight: "500" as const,
    fontSize: Sizes.fontSmall,
  },
  linearGradientContainer: {
    flex: 1,
    justifyContent: "center",
  },
  navButtonText: {
    fontSize: 20,
    letterSpacing: 1,
    color: Colors.subtitlePrimary,
    textShadowColor: "#000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
  },
  navButtonContainer: {
    marginBottom: Sizes.bottomSpace,
    backgroundColor: Colors.buttonBg,
    borderWidth: 4,
    borderColor: Colors.blackDepp,
    borderRadius: 4,
    shadowColor: "#000",
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  shadowStyle: {
    shadowColor: Colors.trueShadow,
    shadowOffset: { width: 6, height: -6 },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 5,
  },
  galleryContainer: {
    marginTop: 3,
    marginBottom: 3,
  },
  galleryTitleContainer: {
    marginBottom: Sizes.bottomSpace,
  },
  quotesSuperContainer: {
    marginTop: 5,
  },
  quotesContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    margin: 5,
  },
  profileSectionCard: {
    padding: 16,
    borderWidth: 4,
    borderColor: Colors.dark,

    marginTop: 16,
    marginBottom: 16,
    backgroundColor: "rgba(0, 0, 0, 0.15)",
  },
  profileSectionTitle: {
    fontSize: 18,
    fontWeight: "700" as const,
    marginBottom: 8,
    color: Colors.mainBorder,
    borderBottomWidth: 1,
    borderBottomColor: Colors.mainBorder,
    paddingBottom: 4,
  },
  profileSectionSubtitle: {
    fontSize: 12,
    color: Colors.subtitlePrimary,
    marginBottom: 10,
    marginTop: 4,
  },
  profileRow: {
    flexDirection: "row" as const,
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 6,
  },
  profileInRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  profileInIcon: {
    marginRight: 8,
    marginLeft: 2,
  },
  profileLabel: {
    fontSize: 14,
    color: Colors.mainBorder,
    fontWeight: "bold",
  },
  profileValue: {
    fontSize: 15,
    fontWeight: "600" as const,
    color: Colors.mainBorder,
  },
  profileButton: {
    marginTop: 12,
    paddingVertical: 10,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: Colors.pink,
  },
  profileButtonText: {
    fontWeight: "600" as const,
  },
  profileInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
  },
  badgeToast: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 74,
    padding: 14,
    backgroundColor: Colors.orangeTitle,
  },
  badgeToastTitle: {
    color: "white",
    fontWeight: "700",
    fontSize: 14,
  },
  badgeToastDescription: {
    color: Colors.mainBorder,
    marginTop: 10,
    fontSize: 12,
  },
  badgeToastDismiss: {
    color: Colors.mainBorder,
    marginTop: 6,
    fontSize: 10,
  },
  badgeListIn: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: Colors.shadowBg,
  },
  badgeListInText: {
    color: Colors.mainBorder,
    fontWeight: "700",
  },
  badgeListInDesc: {
    color: Colors.mainBorder,
    marginTop: 4,
  },
  badgeNone: {
    color: Colors.mainBorder,
  },
  // FAQ
  faqHeaderPanel: {
    borderWidth: 4,
    borderColor: Colors.dark,
    backgroundColor: Colors.darkPinkMuted,
    padding: 10,
    paddingLeft: 20,
    borderRadius: 4,
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    marginTop: 4,
  },
  faqItemTitle: {
    fontSize: 18,
    backgroundColor: Colors.pinkMuted,
    marginTop: 3,
  },
  faqItemRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  faqItemBox: {
    flex: 1,
  },
  faqItemTag: {
    opacity: 0.9,
    marginBottom: 2,
  },
  faqItemInTitle: {
    fontSize: 18,
  },
  faqItemAnswer: {
    marginTop: 10,
    lineHeight: 20,
  },
  // For You screen
  loadingIndicatorView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  recomHeaderView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  recommHeaderLogo: {
    marginLeft: 5,
    padding: 2,
  },
  recomMapView: {
    height: 240,
    marginTop: 12,
    borderRadius: 16,
    overflow: "hidden",
  },
  recomMap: {
    flex: 1,
  },
});
